package main

import (
	"bufio"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/rheodev/cpa-plugin-privacyfilter/detect"
)

// The term file holds the maintained list outside config.yaml, one entry per
// line, so a long list of hostnames stays editable and can be generated by
// cmd/termsgen. Two line forms are accepted and may be mixed:
//
//	p14.local                      literal, kind host
//	p14.local host                 literal with kind
//	markus person ignore_case      literal with kind and the case flag
//	{regex: "[a-z]+\\.home\\.lan", kind: host}
//	{value: "wendler.de", kind: domain}
//
// A line starting with "{" is a YAML flow mapping with the same keys as a
// terms[] entry in config.yaml. A "#" at the start of a line or after white
// space opens a comment; a "#" inside a word belongs to the value, so
// Projekt#42 is one term and not a truncated one. Blank lines are skipped,
// and a byte order mark ahead of the first line is dropped. A line of the
// first form is split on white space: the first word is the literal, the
// optional second word the kind, and the optional word ignore_case sets the
// flag. A literal that needs spaces, that starts with "{" or "#", or that
// carries a "#" behind a space goes into the YAML form.

// termsFileDefaultKind applies when a plain line names no kind.
const termsFileDefaultKind = "host"

// resolveTermsFilePath returns the absolute path of the term file. A relative
// value resolves against pluginDir, like gitleaks_toml and salt_secret_path.
// An empty value means no file.
func resolveTermsFilePath(pluginDir, configured string) string {
	if configured == "" {
		return ""
	}
	if filepath.IsAbs(configured) {
		return configured
	}
	return filepath.Join(pluginDir, configured)
}

// loadTermsFile reads the term file at path. It returns an error for an
// unreadable file or an invalid line, naming the line number, so a plugin in
// pseudonymize mode refuses to start with half a list rather than silently
// scanning with the other half.
func loadTermsFile(path string) ([]TermEntry, error) {
	entries, _, err := loadTermsFileLines(path)
	return entries, err
}

// loadTermsFileLines is loadTermsFile with the line number of every entry,
// so a report about an entry can point at the line the user has to edit.
func loadTermsFileLines(path string) ([]TermEntry, []int, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, nil, err
	}
	defer f.Close()
	entries, lines, err := parseTermsFileLines(f)
	if err != nil {
		return nil, nil, fmt.Errorf("%s: %w", path, err)
	}
	return entries, lines, nil
}

// unsafeTermChars are the characters of a term value that are structure in
// the places a restored value lands: the shell's quotes and metacharacters,
// the comment marks of configuration files, the percent sign of crontab and
// systemd, the path separator, the backslash of patterns and JSON, and the
// control characters, above all the newline and the carriage return.
const unsafeTermChars = "'\"`$;&|<>#%/\\\t\r\n"

// unsafeTermClass names the class of every character in unsafeTermChars,
// for the refusal: the report names the class, never the value.
func unsafeTermClass(r rune) string {
	switch r {
	case '\'', '"':
		return "a quote"
	case '`':
		return "a backtick"
	case '$', ';', '&', '|', '<', '>':
		return "a shell metacharacter (" + string(r) + ")"
	case '#':
		return "a #"
	case '%':
		return "a %"
	case '/':
		return "a /"
	case '\\':
		return "a backslash"
	}
	return "a control character"
}

// termUnsafe names the class of the first character of a term value that is
// in unsafeTermChars or any other control character, and returns the empty
// string for a value that carries none. Letters of any script, digits,
// spaces, dots, dashes, brackets and the like are not judged; only the
// characters in that list are structure for a shell, a comment, a crontab, a
// path or a JSON document. A regular expression is not judged: its
// metacharacters are its own, and what it matches is decided by the text.
// The slash of a network in CIDR form is the one it is meant to have and
// does not count, and neither does the slash of a secret or a fingerprint:
// key material, tokens and SHA256 fingerprints are base64, whose alphabet
// has the slash, and their pseudonyms are opaque tokens that stand where the
// blob stands, never in a path.
func termUnsafe(t TermEntry) string {
	if t.Value == "" {
		return ""
	}
	chars := unsafeTermChars
	switch t.Kind {
	case string(detect.KindCIDR), string(detect.KindSecret), string(detect.KindFingerprint):
		chars = strings.ReplaceAll(chars, "/", "")
	}
	for _, r := range t.Value {
		if strings.ContainsRune(chars, r) || r < 0x20 || r == 0x7f {
			return unsafeTermClass(r)
		}
	}
	return ""
}

// unsafeTermError describes why a term is refused, without quoting the
// value: it names the class of character that was found and the place the
// value would change once restored. The value itself belongs to the list's
// owner and is not written to the log.
func unsafeTermError(class string) error {
	return errors.New("value carries " + class + "; restored into a command line, a configuration line or a patch that was written for the pseudonym it would change what that line does, see README, Known limits. Refused are a quote, a backslash, a shell metacharacter ($ ; & | < > backtick), a #, a %, a / outside a cidr, secret or fingerprint term, and control characters. Write the value as a regular expression if it is meant")
}

// parseTermsFile parses the term file format described above.
func parseTermsFile(r io.Reader) ([]TermEntry, error) {
	entries, _, err := parseTermsFileLines(r)
	return entries, err
}

// parseTermsFileLines is parseTermsFile with the line number of every
// entry.
func parseTermsFileLines(r io.Reader) ([]TermEntry, []int, error) {
	var entries []TermEntry
	var lines []int
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 0, 64*1024), 1<<20)
	lineNo := 0
	for sc.Scan() {
		lineNo++
		line := sc.Text()
		if lineNo == 1 {
			// An editor on Windows writes a byte order mark ahead of the
			// first line. TrimSpace does not remove it, so without this the
			// first term of the list is a different string from the one the
			// user typed and protects nothing. Written as its three bytes
			// because the compiler rejects the character itself in source.
			line = strings.TrimPrefix(line, "\xef\xbb\xbf")
		}
		line = strings.TrimSpace(stripTermsComment(line))
		if line == "" {
			continue
		}
		entry, err := parseTermsLine(line)
		if err != nil {
			return nil, nil, fmt.Errorf("line %d: %w", lineNo, err)
		}
		entries = append(entries, entry)
		lines = append(lines, lineNo)
	}
	if err := sc.Err(); err != nil {
		return nil, nil, err
	}
	return entries, lines, nil
}

// stripTermsComment removes a comment from one line. A '#' opens a comment
// only at the start of a line or after white space, so a term that carries a
// '#' inside its value - Projekt#42, a ticket number, a fragment of a URL -
// is loaded whole. Cutting at every '#' would load such a term truncated and
// leave the part behind the '#' unprotected, which is the opposite of what
// the list is for. A line in the YAML form keeps its '#', because there a
// quoted value may hold one.
func stripTermsComment(line string) string {
	if strings.HasPrefix(strings.TrimSpace(line), "{") {
		return line
	}
	for i := 0; i < len(line); i++ {
		if line[i] != '#' {
			continue
		}
		if i == 0 || line[i-1] == ' ' || line[i-1] == '\t' {
			return line[:i]
		}
	}
	return line
}

// parseTermsLine parses one non-empty, trimmed line.
func parseTermsLine(line string) (TermEntry, error) {
	if strings.HasPrefix(line, "{") {
		var entry TermEntry
		dec := yaml.NewDecoder(strings.NewReader(line))
		dec.KnownFields(true)
		// The message names the line and the form, not the text on it:
		// it reaches the log and, in the blocking state, the client.
		if err := dec.Decode(&entry); err != nil {
			return TermEntry{}, fmt.Errorf("invalid yaml entry (want {value: ..., kind: ..., ignore_case: ...} or {regex: ..., kind: ...}): %w", err)
		}
		if entry.Kind == "" {
			entry.Kind = termsFileDefaultKind
		}
		return entry, nil
	}

	fields := strings.Fields(line)
	entry := TermEntry{Value: fields[0], Kind: termsFileDefaultKind}
	kindSet, flagSet := false, false
	for i, opt := range fields[1:] {
		switch {
		case opt == "ignore_case" && !flagSet:
			entry.IgnoreCase = true
			flagSet = true
		case !kindSet && !flagSet && !strings.ContainsAny(opt, "{}:,"):
			entry.Kind = opt
			kindSet = true
		default:
			// The word itself is not quoted: it may be part of a value
			// with a space, and the message reaches the client.
			return TermEntry{}, fmt.Errorf("unexpected word %d of %d on the line (want: <literal> [kind] [ignore_case]; a value with spaces needs the yaml form)", i+2, len(fields))
		}
	}
	return entry, nil
}

// mergeTerms appends the file entries to the inline list and drops exact
// duplicates, keeping the first occurrence. Two entries are duplicates when
// value, regex, kind and ignore_case all match; the same literal under two
// kinds is kept twice on purpose, and detect.Merge lets the longer or earlier
// hit win.
func mergeTerms(inline, file []TermEntry) []TermEntry {
	out := make([]TermEntry, 0, len(inline)+len(file))
	seen := make(map[TermEntry]bool, len(inline)+len(file))
	for _, list := range [][]TermEntry{inline, file} {
		for _, t := range list {
			if seen[t] {
				continue
			}
			seen[t] = true
			out = append(out, t)
		}
	}
	return out
}
